<?php

namespace AppBundle\Repository;

/**
 * UserOnlineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOnlineRepository extends \Doctrine\ORM\EntityRepository
{
}
